export const DROPDOWN_SCOPE = {
  TAX_STATUS: "TAX_STATUS",
  SIGNER_POSITION_NOM: "SIGNER_POSITION_NOM",
  SIGNER_POSITION_GEN: "SIGNER_POSITION_GEN",
  ACTING_UNDER: "ACTING_UNDER",
  SIGNING_LOCATION: "SIGNING_LOCATION",
} as const;

export type DropdownScope = (typeof DROPDOWN_SCOPE)[keyof typeof DROPDOWN_SCOPE];

